In [1]:
from scipy import linalg

In [2]:
import numpy as np

In [3]:
linalg?

Type:        module
String form: <module 'scipy.linalg' from 'C:\\Users\\fusion\\AppData\\Roaming\\Python\\Python311\\site-packages\\scipy\\linalg\\__init__.py'>
File:        c:\users\fusion\appdata\roaming\python\python311\site-packages\scipy\linalg\__init__.py
Docstring:  
Linear algebra (:mod:`scipy.linalg`)

.. currentmodule:: scipy.linalg

.. toctree::
   :hidden:

   linalg.blas
   linalg.cython_blas
   linalg.cython_lapack
   linalg.interpolative
   linalg.lapack

Linear algebra functions.

.. eventually, we should replace the numpy.linalg HTML link with just `numpy.linalg`

.. seealso::

   `numpy.linalg <https://www.numpy.org/devdocs/reference/routines.linalg.html>`__
   for more linear algebra functions. Note that
   although `scipy.linalg` imports most of them, identically named
   functions from `scipy.linalg` may offer more or slightly differing
   functionality.


Basics

.. autosummary::
   :toctree: generated/

   inv - Find the inverse of a square matrix
   solve - Sol

In [4]:
a=np.array([[1,0,3],[0,1,-2],[1,1,2]])


In [5]:
a

array([[ 1,  0,  3],
       [ 0,  1, -2],
       [ 1,  1,  2]])

In [6]:
linalg.det(a)

0.9999999999999998

In [7]:
linalg.inv(a)

array([[ 4.,  3., -3.],
       [-2., -1.,  2.],
       [-1., -1.,  1.]])

In [8]:
a=np.array([[7,2],[4,5]])
a

array([[7, 2],
       [4, 5]])

In [10]:
b=np.array([8,10])
b

array([ 8, 10])

In [11]:
linalg.solve(a,b)

array([0.74074074, 1.40740741])

In [12]:
a=np.array([[2,4,6],[2,-3,-4],[3,4,5]])

In [13]:
b=np.array([-12,15,-8])

In [14]:
linalg.solve(a,b)

array([ 2., -1., -2.])

In [15]:
a


array([[ 2,  4,  6],
       [ 2, -3, -4],
       [ 3,  4,  5]])

In [16]:
linalg.det(a)

16.000000000000007

In [18]:
(x,y,z)=linalg.solve(a,b)

In [19]:
x

2.0000000000000004

In [20]:
y

-1.0000000000000013

In [21]:
z

-1.9999999999999991

In [24]:
a=np.array([[2,1],[4,2]])

In [25]:
b=np.array([5,10])

In [26]:
linalg.det(a)

0.0

In [27]:
linalg.inv(a)

LinAlgError: singular matrix

In [28]:
linalg.solve(a,b)

LinAlgError: Matrix is singular.