In [1]:
import pandas as pd
import numpy as np

In [2]:
grades=pd.read_csv('C:/ejercicios/grades.csv')

In [3]:
grades


exam  student_id  grade
0      1           1   86.0
1      1           2   65.0
2      1           3   70.0
3      1           4   98.0
4      1           5   89.0
5      1           6    NaN
6      1           7   75.0
7      1           8   56.0
8      1           9   90.0
9      1          10   81.0
10     2           1   79.0
11     2           2   60.0
12     2           3   78.0
13     2           4   75.0
14     2           5    NaN
15     2           6   80.0
16     2           7   87.0
17     2           8   82.0
18     2           9   95.0
19     2          10   96.0
20     3           1   78.0
21     3           2   80.0
22     3           3   87.0
23     3           4    NaN
24     3           5   89.0
25     3           6   90.0
26     3           7  100.0
27     3           8   72.0
28     3           9   73.0
29     3          10   75.0
30     4           1    NaN
31     4           2   80.0
32     4           3   81.0
33     4           4   82.0
34     4           5   83.0
35     4           6   84.0
36     4           7   85.0
37     4           8   86.0
38     4           9   87.0
39     4          10   88.0
40     5           1   90.0
41     5           2    NaN
42     5           3   91.0
43     5           4   92.0
44     5           5   93.0
45     5           6   94.0
46     5           7   95.0
47     5           8   96.0
48     5           9   97.0
49     5          10   98.0

In [4]:
grades.head(10)

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [5]:
grades.iloc[:10]

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [6]:
grades.iloc[2:10]

exam  student_id  grade
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [7]:
grades.iloc[20:30]

exam  student_id  grade
20     3           1   78.0
21     3           2   80.0
22     3           3   87.0
23     3           4    NaN
24     3           5   89.0
25     3           6   90.0
26     3           7  100.0
27     3           8   72.0
28     3           9   73.0
29     3          10   75.0

In [11]:
grades['grade'].fillna(0)

0      86.0
1      65.0
2      70.0
3      98.0
4      89.0
5       0.0
6      75.0
7      56.0
8      90.0
9      81.0
10     79.0
11     60.0
12     78.0
13     75.0
14      0.0
15     80.0
16     87.0
17     82.0
18     95.0
19     96.0
20     78.0
21     80.0
22     87.0
23      0.0
24     89.0
25     90.0
26    100.0
27     72.0
28     73.0
29     75.0
30      0.0
31     80.0
32     81.0
33     82.0
34     83.0
35     84.0
36     85.0
37     86.0
38     87.0
39     88.0
40     90.0
41      0.0
42     91.0
43     92.0
44     93.0
45     94.0
46     95.0
47     96.0
48     97.0
49     98.0
Name: grade, dtype: float64

In [12]:
grades.iloc[:10]

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [13]:
grades.loc[grades['exam']==1]

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0
5     1           6    NaN
6     1           7   75.0
7     1           8   56.0
8     1           9   90.0
9     1          10   81.0

In [14]:
grades.loc[grades['exam']==1]['grade'].mean()

78.88888888888889

In [15]:
grades.loc?


Type:        property
String form: <property object at 0x00000197E479FFB0>
Docstring:  
Access a group of rows and columns by label(s) or a boolean array.

``.loc[]`` is primarily label based, but may also be used with a
boolean array.

Allowed inputs are:

- A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
  interpreted as a *label* of the index, and **never** as an
  integer position along the index).
- A list or array of labels, e.g. ``['a', 'b', 'c']``.
- A slice object with labels, e.g. ``'a':'f'``.

  .. warning:: Note that contrary to usual python slices, **both** the
      start and the stop are included

- A boolean array of the same length as the axis being sliced,
  e.g. ``[True, False, True]``.
- An alignable boolean Series. The index of the key will be aligned before
  masking.
- An alignable Index. The Index of the returned selection will be the input.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output f

In [17]:
exam1_mean=grades.loc[grades['exam']==1]['grade'].mean()
exam1_mean

78.88888888888889

In [18]:
grades.loc[grades['grade'] >= 70]['grade'].values

array([ 86.,  70.,  98.,  89.,  75.,  90.,  81.,  79.,  78.,  75.,  80.,
        87.,  82.,  95.,  96.,  78.,  80.,  87.,  89.,  90., 100.,  72.,
        73.,  75.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.])

In [19]:
grades.loc[grades['grade'] < 70]['grade'].values

array([65., 56., 60.])

In [20]:
array0 = np.array([])

In [21]:
array0

array([], dtype=float64)

In [23]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [25]:
array1=np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [26]:
list2=[[1,2,3],[4,5,6],[7,8,9]]

In [27]:
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
array2=np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones((7,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [38]:
np.linspace(0,1,22)

array([0.        , 0.04761905, 0.0952381 , 0.14285714, 0.19047619,
       0.23809524, 0.28571429, 0.33333333, 0.38095238, 0.42857143,
       0.47619048, 0.52380952, 0.57142857, 0.61904762, 0.66666667,
       0.71428571, 0.76190476, 0.80952381, 0.85714286, 0.9047619 ,
       0.95238095, 1.        ])

In [48]:
array_radom=np.random.randint(1,20,10)

In [49]:
array_radom

array([13, 15, 12, 17, 16, 16, 11, 15, 16,  8])

In [50]:
array_radom.min()

8

In [51]:
array_radom.max()

17

In [53]:
#La posición del mínimo
array_radom.argmin()

9

In [54]:
#La posición del máximo
array_radom.argmax()

3

In [55]:
array_radom.shape

(10,)

In [56]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
array2[1][1]

5

In [58]:
array2[0][0]


1

In [59]:
array2[2][2]


9

In [60]:
array2[1][2]

6